Update Task_3_2 on Jan 20th
Tatsup/210107_Task_3 pull request #2
Opened 2021-01-21 11:37 UTC by Tatsup

課題③-2

2021-01-23 12:24 UTC, myzktkyk requested changes
動作は問題ありませんでした。
1点指摘をしています。

2021-01-23 12:24 UTC, myzktkyk commented on js/main.js
> +      buildNodeByForeach(table);// 表示するノードを組み立て（ループ処理）
ちょっと今更な指摘で恐縮なのですが…このメソッド名にやや違和感を覚えます。
一見それっぽいのですが抽象的な言葉が並んでいて、実際「何をしてくれるのか」がイマイチはっきりしません。

同じような感じで私が名づけるなら `buildTableRows` とかにしそうです。

2021-01-23 14:43 UTC, Tatsup commented on js/main.js
> +      buildNodeByForeach(table);// 表示するノードを組み立て（ループ処理）
builtToDoListTableに修正しました．

2021-01-25 03:36 UTC, Kenichiro-Kiwaki reviewed
コメント致しましたので、ご確認ください。

2021-01-25 03:36 UTC, Kenichiro-Kiwaki commented on js/main.js
> +    // deleteButton.id = 'delete';
他のコメントアウトについては説明する目的があり必要性を感じますが、
こちらについては残しておく理由がないように思うのですがどうでしょうか。
不要なコードやコメントアウトは削除するようにしましょう。
予期せぬエラーやバグを防ぐためです。

2021-01-25 03:36 UTC, Kenichiro-Kiwaki commented on js/main.js
> +    const WorkingButton = createButton('作業中');
他と同様にローワーキャメルケースで命名しましょう。

2021-01-25 11:44 UTC, Tatsup commented on js/main.js
> +    // deleteButton.id = 'delete';
削除しました．

2021-01-25 12:01 UTC, Tatsup commented on js/main.js
> +    const WorkingButton = createButton('作業中');
修正しました．

2021-01-25 13:01 UTC, merged